-- EMERGENCY FIX - Run this in Supabase SQL Editor NOW
-- This sets the super admin password to 'fehin0706' with a hash generated by bcryptjs

-- Update super admin password
UPDATE users
SET password_hash = '$2a$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5ztP.eKzV7W.u',
    role = 'super_admin'
WHERE email = 'fehintoluwaolu@gmail.com';

-- Verify the update
SELECT 
    email, 
    role,
    CASE 
        WHEN password_hash LIKE '$2a$12$%' OR password_hash LIKE '$2b$12$%' THEN '✅ Valid Hash'
        ELSE '❌ Invalid Hash'
    END as hash_status,
    LENGTH(password_hash) as hash_length
FROM users
WHERE email = 'fehintoluwaolu@gmail.com';
