-- RUN 4th: Add missing columns to markets table (part 1 of 3)

select public.add_column_if_missing('markets', 'status', 'text', quote_literal('active'));
select public.add_column_if_missing('markets', 'state', 'text', quote_literal('trading'));
select public.add_column_if_missing('markets', 'market_type', 'text', quote_literal('binary'));
select public.add_column_if_missing('markets', 'currency', 'text', quote_literal('NGN'));
select public.add_column_if_missing('markets', 'updated_at', 'timestamptz', 'now()');
select public.add_column_if_missing('markets', 'yes_label', 'text', quote_literal('YES'));
select public.add_column_if_missing('markets', 'no_label', 'text', quote_literal('NO'));
select public.add_column_if_missing('markets', 'yes_price', 'numeric', '0.5');
select public.add_column_if_missing('markets', 'no_price', 'numeric', '0.5');
select public.add_column_if_missing('markets', 'pricing_model', 'text', quote_literal('dynamic'));
select public.add_column_if_missing('markets', 'starting_yes_price', 'numeric');
select public.add_column_if_missing('markets', 'starting_no_price', 'numeric');
select public.add_column_if_missing('markets', 'pool_amount_smallest_unit', 'bigint', '0');
select public.add_column_if_missing('markets', 'settlement_pool_smallest_unit', 'bigint', '0');
select public.add_column_if_missing('markets', 'yes_pool_smallest_unit', 'bigint', '0');
select public.add_column_if_missing('markets', 'no_pool_smallest_unit', 'bigint', '0');
select public.add_column_if_missing('markets', 'yes_volume_smallest_unit', 'bigint', '0');
select public.add_column_if_missing('markets', 'no_volume_smallest_unit', 'bigint', '0');
select public.add_column_if_missing('markets', 'total_volume_smallest_unit', 'bigint', '0');
select public.add_column_if_missing('markets', 'seed_liquidity_yes_smallest_unit', 'bigint', '0');
select public.add_column_if_missing('markets', 'seed_liquidity_no_smallest_unit', 'bigint', '0');
select public.add_column_if_missing('markets', 'total_yes_shares', 'numeric', '0');
select public.add_column_if_missing('markets', 'total_no_shares', 'numeric', '0');
select public.add_column_if_missing('markets', 'participant_count', 'integer', '0');
select public.add_column_if_missing('markets', 'trade_count', 'integer', '0');
select public.add_column_if_missing('markets', 'close_date', 'timestamptz');
select public.add_column_if_missing('markets', 'trading_close_at', 'timestamptz');
select public.add_column_if_missing('markets', 'resolution_date', 'timestamptz');
select public.add_column_if_missing('markets', 'resolution_source', 'text');
select public.add_column_if_missing('markets', 'resolution_instructions', 'text');
select public.add_column_if_missing('markets', 'outcome', 'text');
select public.add_column_if_missing('markets', 'winning_outcome', 'text');
select public.add_column_if_missing('markets', 'resolved_outcome', 'text');
select public.add_column_if_missing('markets', 'resolved_at', 'timestamptz');
select public.add_column_if_missing('markets', 'resolved_by', 'uuid');
select public.add_column_if_missing('markets', 'refunded_at', 'timestamptz');
select public.add_column_if_missing('markets', 'refund_reason', 'text');
select public.add_column_if_missing('markets', 'refund_status', 'text');
select public.add_column_if_missing('markets', 'refunded_by', 'uuid');
select public.add_column_if_missing('markets', 'payout_status', 'text');
select public.add_column_if_missing('markets', 'payout_completed_at', 'timestamptz');
